//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnp_Imagenes
    {
        public int id_Imagen { get; set; }
        public string NO_PROYECTO { get; set; }
        public string IMGPRODUCTO { get; set; }
        public string IMGLOTIFICADO { get; set; }
        public string IMGCORRUGADO { get; set; }
        public Nullable<System.DateTime> SYSTEM_DATE { get; set; }
    }
}
