//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnp_Firma
    {
        public int id_Autoriza { get; set; }
        public string Usuario { get; set; }
        public string Depto { get; set; }
        public string Tipo { get; set; }
        public string Correo { get; set; }
        public string pa { get; set; }
    }
}
