//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnp_Codigo_barras
    {
        public int id_codigo { get; set; }
        public string NO_PROYECTO { get; set; }
        public string EAN_13 { get; set; }
        public string EAN_14 { get; set; }
        public string CODIGO_ADICIONAL { get; set; }
        public Nullable<System.DateTime> SYSTEM_DATE { get; set; }
    }
}
