//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnp_Fisicoquimicas
    {
        public int id_Fisicoquimicas { get; set; }
        public string NO_PROYECTO { get; set; }
        public string FORMULA { get; set; }
        public string CONTENIDO_NETO { get; set; }
        public string CODIGO_ROSS_ELAB { get; set; }
        public string DENSIDAD { get; set; }
        public string PH { get; set; }
        public string VISCOCIDAD { get; set; }
        public string TEXTURA { get; set; }
        public Nullable<System.DateTime> SYSTEM_DATE { get; set; }
    }
}
