//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnp_CorrugadoBrief
    {
        public int id_Corrugado { get; set; }
        public string NO_PROYECTO { get; set; }
        public string MATERIAL { get; set; }
        public string TERMINADO { get; set; }
        public string PZAS { get; set; }
        public string OTROSCORR { get; set; }
        public Nullable<System.DateTime> SYSTEM_DATE { get; set; }
    }
}
