//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnp_Proyecto_Firma
    {
        public string NO_PROYECTO { get; set; }
        public string SOLICITO { get; set; }
        public string DNP { get; set; }
        public string COSTOS { get; set; }
        public string INVYDES { get; set; }
        public string ROSSERP { get; set; }
        public string INGMAT { get; set; }
        public string DPLANTA { get; set; }
        public string CALIDAD { get; set; }
        public string HACCP { get; set; }
        public string VENTAS { get; set; }
        public Nullable<System.DateTime> SYSTEM_DATE { get; set; }
    }
}
