//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnp_FormulaBrief
    {
        public int id_formula { get; set; }
        public string NO_PROYECTO { get; set; }
        public string TIPO { get; set; }
        public string DESC_TIPO { get; set; }
        public string INGREDIENTES { get; set; }
        public string COLOR { get; set; }
        public string COLOROTROS { get; set; }
        public string CLAIMS { get; set; }
        public string TERMINADOS { get; set; }
        public string APARIENCIA { get; set; }
        public string OTROSFORMULA { get; set; }
        public string IMAGENREFERENCIA { get; set; }
        public Nullable<System.DateTime> SYSTEM_DATE { get; set; }
        public string FPS { get; set; }
        public string OTROSFPS { get; set; }
    }
}
