//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnp_Cabecera
    {
        public int id_proyecto { get; set; }
        public string NO_PROYECTO { get; set; }
        public int ID_CLIENTE { get; set; }
        public System.DateTime FECHA_NOTI { get; set; }
        public System.DateTime FECHA_LANZ { get; set; }
        public string TIPO_PROYECTO { get; set; }
        public string CODIGO_CLIENTE { get; set; }
        public Nullable<int> ID_ESTATUS { get; set; }
        public Nullable<System.DateTime> SYSTEM_DATE { get; set; }
    }
}
