//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnp_FirmasBrief
    {
        public int id_autorizaBrief { get; set; }
        public string USR { get; set; }
        public string AREA { get; set; }
        public string CORREO { get; set; }
        public Nullable<System.DateTime> SYTEM_DATE { get; set; }
    }
}
