//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnp_Botella_Brief
    {
        public int id_botellaBrief { get; set; }
        public string NO_PROYECTO { get; set; }
        public string GRAMAJE { get; set; }
        public string FORMA { get; set; }
        public string MATERIAL { get; set; }
        public string COLOR { get; set; }
        public string OTROSMATERIAL { get; set; }
        public string OTROSFORMA { get; set; }
        public Nullable<System.DateTime> SYSTEM_DATE { get; set; }
    }
}
