//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnp_Cabecera_Cotiza
    {
        public int id_proyecto { get; set; }
        public string NO_PROYECTO { get; set; }
        public Nullable<int> SOLICITA { get; set; }
        public string CLIENTE { get; set; }
        public string PRODUCTO { get; set; }
        public int CAJAS { get; set; }
        public string LINEA { get; set; }
        public Nullable<int> PERSONAS { get; set; }
        public Nullable<int> CAJASTURNO { get; set; }
        public string FORMULA { get; set; }
        public Nullable<int> CONTENIDO { get; set; }
        public string CODIGOFORMULA { get; set; }
        public string EQUIPO { get; set; }
        public Nullable<System.DateTime> SYSTEM_DATE { get; set; }
        public string USRMODIFY { get; set; }
    }
}
