//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnp_CostoCot
    {
        public int id_cost { get; set; }
        public string NO_PROYECTO { get; set; }
        public string COST_PIEZA { get; set; }
        public string COST_CAJA { get; set; }
        public string INCOTERM { get; set; }
        public string VIGENCIA { get; set; }
        public string MOQ_COMECIAL { get; set; }
    }
}
