//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnp_Embalaje
    {
        public int id_Embalaje { get; set; }
        public string NO_PROYECTO { get; set; }
        public string UNIDADES { get; set; }
        public string CORRUGADOS { get; set; }
        public string CAMAS { get; set; }
        public string CAJAS { get; set; }
        public string TIPO_TARIMA { get; set; }
        public string ALTURA { get; set; }
        public Nullable<System.DateTime> SYSTEM_DATE { get; set; }
        public string PESO { get; set; }
    }
}
