//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnp_Producto
    {
        public int id_Producto { get; set; }
        public string NO_PROYECTO { get; set; }
        public string PRODUCTO_DES { get; set; }
        public string CODIGO_ROSS { get; set; }
        public Nullable<int> CAJAS_ESTIMADAS { get; set; }
        public string REG_SAN { get; set; }
        public string CADUCIDAD { get; set; }
        public Nullable<System.DateTime> SYSTEM_DATE { get; set; }
    }
}
