//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_PonderacionTapa
    {
        public string NO_PROYECTO { get; set; }
        public string TIPO { get; set; }
        public int PondTipo { get; set; }
        public string MATERIAL { get; set; }
        public int PondMaterial { get; set; }
        public string COLOR { get; set; }
        public int PondColor { get; set; }
        public string TERMINADO { get; set; }
        public int PondTerminado { get; set; }
        public string LINNER { get; set; }
        public int PondLinner { get; set; }
    }
}
