//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_dnp_FundaBrief
    {
        public int id_funda { get; set; }
        public string NO_PROYECTO { get; set; }
        public string MATETI { get; set; }
        public string TERMINADOETI { get; set; }
        public string MATFUNDA { get; set; }
        public string TERMINADOFUNDA { get; set; }
        public string IMPRESION { get; set; }
        public string OTROFUNDA { get; set; }
        public Nullable<System.DateTime> SYSTEM_DATE { get; set; }
        public string Expr1 { get; set; }
        public string TERMINADOTUBO { get; set; }
        public string MATTUBO { get; set; }
    }
}
