//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PonderacionFunda
    {
        public string NO_PROYECTO { get; set; }
        public string MATETI { get; set; }
        public int PondMatEti { get; set; }
        public string TERMINADOETI { get; set; }
        public int PondTerminadoEti { get; set; }
        public string MATFUNDA { get; set; }
        public int PondMatFunda { get; set; }
        public string TERMINADOFUNDA { get; set; }
        public int PondTerminadoFunda { get; set; }
        public string IMPRESION { get; set; }
        public int PondImpre { get; set; }
        public string TERMINADOTUBO { get; set; }
        public int PondTubo { get; set; }
        public string MATTUBO { get; set; }
        public int PondTerminadoTubo { get; set; }
    }
}
