//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_dnp_proyectosBrief
    {
        public int id_proyecto { get; set; }
        public string NO_PROYECTO { get; set; }
        public string CLIENTE { get; set; }
        public string PRODUCTO { get; set; }
        public Nullable<System.DateTime> SYSTEM_DATE { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public Nullable<int> CAJAS { get; set; }
        public string OTRO { get; set; }
        public string VENTAS { get; set; }
        public string COSTOS { get; set; }
        public string DESARROLLO { get; set; }
        public string DIRECCION { get; set; }
        public string ID_MAQUILA { get; set; }
        public string TIPO_MAQUILA { get; set; }
        public Nullable<int> ORDEN { get; set; }
        public Nullable<int> Puntos { get; set; }
        public string RIESGO { get; set; }
        public string TIPO_PROYECTO { get; set; }
        public string VALIDACION { get; set; }
    }
}
