//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_PonderacionBotella
    {
        public string NO_PROYECTO { get; set; }
        public string Forma { get; set; }
        public int PondForma { get; set; }
        public string MATERIAL { get; set; }
        public int PondMaterial { get; set; }
        public string Color { get; set; }
        public int PondColor { get; set; }
        public string PondGramaje { get; set; }
    }
}
