//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_dnpFirmasVentasCotiza
    {
        public string NO_PROYECTO { get; set; }
        public string NOMBRE { get; set; }
        public string FIRMA { get; set; }
        public string AREA { get; set; }
    }
}
