//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_dnp_ProyectosFormula
    {
        public string NO_PROYECTO { get; set; }
        public Nullable<int> ORDEN_TIPO { get; set; }
        public Nullable<int> PONDERACION_TIPO { get; set; }
        public Nullable<int> ORDEN_COLOR { get; set; }
        public Nullable<int> PONDERACION_COLOR { get; set; }
        public Nullable<int> ORDEN_TERMINADOS { get; set; }
        public Nullable<int> PONDERACION_TERMINADOS { get; set; }
        public string DESC_TIPO { get; set; }
        public string INGREDIENTES { get; set; }
        public string COLOROTROS { get; set; }
        public string CLAIMS { get; set; }
        public string APARIENCIA { get; set; }
        public string OTROSFORMULA { get; set; }
        public string IMAGENREFERENCIA { get; set; }
        public string LEGAL { get; set; }
        public string OTROS { get; set; }
        public string REQUIS_LEGAL { get; set; }
        public string ESPECIFICACIONES { get; set; }
        public Nullable<int> ORDEN_FPS { get; set; }
        public string OTROSFPS { get; set; }
    }
}
