//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PonderacionFormula
    {
        public string NO_PROYECTO { get; set; }
        public Nullable<int> ORDEN_TIPO { get; set; }
        public int PondTipo { get; set; }
        public string PondIngredientes { get; set; }
        public Nullable<int> ORDEN_COLOR { get; set; }
        public int PondColor { get; set; }
        public int PondClaims { get; set; }
        public Nullable<int> ORDEN_TERMINADOS { get; set; }
        public int PondTerminados { get; set; }
        public int PondApariencia { get; set; }
    }
}
