//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_dnp_TapaBrief
    {
        public int id_tapa { get; set; }
        public string NO_PROYECTO { get; set; }
        public string TIPO { get; set; }
        public string MATERIAL { get; set; }
        public string COLOR { get; set; }
        public string TERMINADO { get; set; }
        public string LINNER { get; set; }
        public string OTROSTIPO { get; set; }
        public string OTROSMATERIAL { get; set; }
        public string OTROSLINNER { get; set; }
        public string COLORTEXT { get; set; }
        public Nullable<System.DateTime> SYSTEM_DATE { get; set; }
    }
}
