//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_dnpProyectosTapa
    {
        public string NO_PROYECTO { get; set; }
        public Nullable<int> ORDEN_TIPO { get; set; }
        public Nullable<int> PONDERACION_TIPO { get; set; }
        public Nullable<int> ORDEN_MATERIAL { get; set; }
        public Nullable<int> PONDERACION_MATERIAL { get; set; }
        public Nullable<int> ORDEN_COLOR { get; set; }
        public Nullable<int> PONDERACION_COLOR { get; set; }
        public Nullable<int> ORDEN_TERMINADO { get; set; }
        public Nullable<int> PONDERACION_TERMINADO { get; set; }
        public Nullable<int> ORDEN_LINNER { get; set; }
        public Nullable<int> PONDERACION_LINNER { get; set; }
        public string OTROSTIPO { get; set; }
        public string OTROSMATERIAL { get; set; }
        public string OTROSLINNER { get; set; }
        public string COLORTEXT { get; set; }
    }
}
