//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TG_DNP
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_dnpProyectosCorrugado
    {
        public string NO_PROYECTO { get; set; }
        public Nullable<int> ORDEN_MATERIAL { get; set; }
        public Nullable<int> PONDERACION_MATERIAL { get; set; }
        public Nullable<int> ORDEN_TERMINADO { get; set; }
        public Nullable<int> PONDERACION_TERMINADO { get; set; }
        public Nullable<int> ORDEN_PIEZAS { get; set; }
        public Nullable<int> PONDERACION_PIEZAS { get; set; }
        public string PZAS { get; set; }
        public string OTROSCORR { get; set; }
    }
}
